const data = [
  {
    id: 1,
    name: "Charlotte Eade",
    location: "Brazil",
    joined_on: "2021-09-12 20:55:54",
    followers: 39,
    categories: "Fashion",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 2,
    name: "Lindy Vassie",
    location: "Ecuador",
    joined_on: "2021-09-17 14:05:33",
    followers: 49,
    categories: "Food",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 3,
    name: "Tessi Hardage",
    location: "Indonesia",
    joined_on: "2021-09-18 12:59:56",
    followers: 25,
    categories: "Car",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 4,
    name: "Tammie Mitchelmore",
    location: "Turkmenistan",
    joined_on: "2022-08-02 21:17:56",
    followers: 77,
    categories: "Fashion",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 5,
    name: "Marcos Gogin",
    location: "Philippines",
    joined_on: "2022-06-23 01:29:49",
    followers: 90,
    categories: "Fashion",
    gender: "Male",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 6,
    name: "Lorena Pudan",
    location: "Haiti",
    joined_on: "2021-06-23 10:36:31",
    followers: 32,
    categories: "Gadgets",
    gender: "Male",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 7,
    name: "Giavani Standbridge",
    location: "Philippines",
    joined_on: "2022-04-06 01:50:31",
    followers: 10,
    categories: "Food",
    gender: "Male",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 8,
    name: "Wini Brownsell",
    location: "Albania",
    joined_on: "2021-11-19 07:46:22",
    followers: 37,
    categories: "Fashion",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 9,
    name: "Leora Finlaison",
    location: "Indonesia",
    joined_on: "2022-01-16 13:44:03",
    followers: 46,
    categories: "Food",
    gender: "Female",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
  {
    id: 10,
    name: "Duffie Klemz",
    location: "Ukraine",
    joined_on: "2022-03-22 08:43:34",
    followers: 63,
    categories: "Fashion",
    gender: "Male",
    imageURL: `https://i.pravatar.cc/300?img=${Math.floor(Math.random() * 10)}`,
  },
];

module.exports = { data };
